<a href="https://colab.research.google.com/github/Nargis45/Book_recommendation_system/blob/main/Book_recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing modules
import pandas as pd
import sys
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
# This is to supress the warning messages (if any) generated in our code
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive     
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
books=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Books.csv')
users=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Users.csv')
ratings=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ratings.csv')

In [ ]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [ ]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [ ]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [ ]:
def change_url(param):
  if isinstance(param,str):
    param=param.replace('http','https')
  return param

In [ ]:
books['Image-URL']=books['Image-URL-L'].apply(change_url)

In [ ]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Image-URL
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,https://images.amazon.com/images/P/0195153448....
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,https://images.amazon.com/images/P/0002005018....
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,https://images.amazon.com/images/P/0060973129....
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,https://images.amazon.com/images/P/0374157065....
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,https://images.amazon.com/images/P/0393045218....

In [ ]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
Image-URL              3
dtype: int64

In [ ]:
books['Image-URL'].fillna('https://www.google.com/url?sa=i&url=https%3A%2F%2Fpustakkosh.com%2F&psig=AOvVaw35myZNAf6L5HfH4cxgHgyH&ust=1669578437698000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCIit7b7OzPsCFQAAAAAdAAAAABAE',inplace=True)

In [ ]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
Image-URL              0
dtype: int64

In [ ]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [ ]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [ ]:
books.duplicated().sum()

0

In [ ]:
users.duplicated().sum()

0

In [ ]:
ratings.duplicated().sum()

0

# **Popularity Based Recommendation System**

**Considering top 50 books with min. of 100 votes and have highest average rating**

In [ ]:
#Merge ratings and books
ratings_with_name=ratings.merge(books, on='ISBN')

In [ ]:
#no. of ratings on each book
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [ ]:
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)

In [ ]:
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [ ]:
#avg. rating on each book
avg_rating_df=ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'},inplace=True)
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [ ]:
popular_df=num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [ ]:
popular_df=popular_df[popular_df['num_ratings']>=250].sort_values('avg_ratings',ascending=False).head(50)

In [ ]:
popular_df=popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author', 'Image-URL','num_ratings', 'avg_ratings']]

In [ ]:
popular_df['avg_ratings']=popular_df['avg_ratings'].round(decimals=2)
popular_df

,Book-Title,Book-Author,Image-URL,num_ratings,avg_ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,https://images.amazon.com/images/P/0439136350....,428,5.85
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,https://images.amazon.com/images/P/0439139597....,387,5.82
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,https://images.amazon.com/images/P/0590353403....,278,5.74
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,https://images.amazon.com/images/P/043935806X....,347,5.50
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,https://images.amazon.com/images/P/0439064872....,556,5.18
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,https://images.amazon.com/images/P/0345339681....,281,5.01
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,https://images.amazon.com/images/P/0345339703....,368,4.95
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,https://images.amazon.com/images/P/059035342X....,575,4.90
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,https://images.amazon.com/images/P/0345339711....,260,4.88
39,To Kill a Mockingbird,Harper Lee,https://images.amazon.com/images/P/0446310786....,510,4.70
47,The Da Vinci Code,Dan Brown,https://images.amazon.com/images/P/0385504209....,898,4.64
53,The Five People You Meet in Heaven,Mitch Albom,https://images.amazon.com/images/P/0786868716....,430,4.55
55,The Catcher in the Rye,J.D. Salinger,https://images.amazon.com/images/P/0316769487....,449,4.55
62,The Lovely Bones: A Novel,Alice Sebold,https://images.amazon.com/images/P/0316666343....,1295,4.47
63,1984,George Orwell,https://images.amazon.com/images/P/0451524934....,284,4.45
72,Prodigal Summer: A Novel,Barbara Kingsolver,https://images.amazon.com/images/P/0060959037....,253,4.45
73,Neverwhere,Neil Gaiman,https://images.amazon.com/images/P/0380789019....,265,4.45
78,The Secret Life of Bees,Sue Monk Kidd,https://images.amazon.com/images/P/0142001740....,774,4.45
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,https://images.amazon.com/images/P/0060392452....,283,4.36
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,https://images.amazon.com/images/P/0385484518....,493,4.35
88,The Red Tent (Bestselling Backlist),Anita Diamant,https://images.amazon.com/images/P/0312195516....,723,4.33
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,https://images.amazon.com/images/P/0671461494....,268,4.33
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,https://images.amazon.com/images/P/0805063897....,335,4.29
100,Into the Wild,Jon Krakauer,https://images.amazon.com/images/P/0385486804....,252,4.27
103,Fahrenheit 451,Ray Bradbury,https://images.amazon.com/images/P/3257208626....,409,4.26
116,Girl with a Pearl Earring,Tracy Chevalier,https://images.amazon.com/images/P/0452282152....,526,4.22
117,Outlander,DIANA GABALDON,https://images.amazon.com/images/P/0440222915....,283,4.17
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,https://images.amazon.com/images/P/0446672211....,585,4.11
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,https://images.amazon.com/images/P/0449005615....,275,4.10
126,Life of Pi,Yann Martel,https://images.amazon.com/images/P/0151008116....,664,4.09
130,The Bean Trees,Barbara Kingsolver,https://images.amazon.com/images/P/0060915544....,389,4.09
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,https://images.amazon.com/images/P/1558743669....,265,4.09
135,ANGELA'S ASHES,Frank McCourt,https://images.amazon.com/images/P/0684874350....,279,4.08
137,Good in Bed,Jennifer Weiner,https://images.amazon.com/images/P/0743418174....,490,4.06
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,https://images.amazon.com/images/P/0060938455....,321,4.04
140,American Gods,Neil Gaiman,https://images.amazon.com/images/P/0380789035....,302,4.01
141,Skipping Christmas,JOHN GRISHAM,https://images.amazon.com/images/P/0385505833....,322,4.01
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,https://images.amazon.com/images/P/0842329129....,318,4.00
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,https://images.amazon.com/images/P/037582345X....,336,4.00
157,The Color Purple,Alice Walker,https://images.amazon.com/images/P/0671617028....,314,3.96
163,Silence of the Lambs,Thomas Harris,https://images.amazon.com/images/P/0312924585....,256,3.96
166,About a Boy,Nick Hornby,https://images.amazon.com/images/P/1573227331....,262,3.90
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,https://images.amazon.com/images/P/0312265840....,278,3.89
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,https://images.amazon.com/images/P/0062502174....,266,3.88
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,https://images.amazon.com/images/P/0312983867....,269,3.83
182,Suzanne's Diary for Nicholas,James Patterson,https://images.amazon.com/images/P/0316969443....,457,3.82
186,Lord of the Flies,William Gerald Golding,https://images.amazon.com/images/P/0399501487....,259,3.82
192,A Prayer for Owen Meany,John Irving,https://images.amazon.com/images/P/0345361792....,413,3.80
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,https://images.amazon.com/images/P/0345313860....,301,3.78
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,https://images.amazon.com/images/P/0316284955....,356,3.77

# **Collaborative Based Recommendation System**

**Considering users who have given min. 250 ratings and the books with min. 50 votes**

In [ ]:
x=ratings_with_name.groupby('User-ID').count()['Book-Rating']>250
padhe_likhe_users=x[x].index

In [ ]:
filtered_rating=ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]

In [ ]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books=y[y].index

In [ ]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Fine Balance',
       'A Heartbreaking Work of Staggering Genius',
       ...
       'Wild Animus', 'Winter Moon', 'Winter Solstice', 'Wish You Well',
       'Without Remorse', 'Wuthering Heights', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=574)

In [ ]:
final_ratings=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [ ]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Image-URL
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,https://images.amazon.com/images/P/0446520802....
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,https://images.amazon.com/images/P/0446520802....
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,https://images.amazon.com/images/P/0446520802....
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,https://images.amazon.com/images/P/0446520802....
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,https://images.amazon.com/images/P/0446520802....
...,...,...,...,...,...,...,...,...,...,...,...
1025422,264317,0833563505,0,The Queen of the Damned (Vampire Chronicles (P...,Anne Rice,1999,Sagebrush Bound,http://images.amazon.com/images/P/0833563505.0...,http://images.amazon.com/images/P/0833563505.0...,http://images.amazon.com/images/P/0833563505.0...,https://images.amazon.com/images/P/0833563505....
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,https://images.amazon.com/images/P/0531001725....
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,https://images.amazon.com/images/P/0440910927....
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,https://images.amazon.com/images/P/B0001PIOX4....
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,https://images.amazon.com/images/P/1586210661....

In [ ]:
pt=final_ratings.pivot_table(index='Book-Title',columns='User-ID', values='Book-Rating')

In [ ]:
pt.shape

(574, 613)

In [ ]:
pt.fillna(0,inplace=True)

In [ ]:
pt

User-ID,254,2276,2766,3363,4385,6251,6543,6575,7158,7346,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wuthering Heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#to find similar books
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity_score=cosine_similarity(pt)

In [ ]:
similarity_score

array([[1.        , 0.12637786, 0.01584756, ..., 0.1387288 , 0.08450515,
        0.0521102 ],
       [0.12637786, 1.        , 0.28824811, ..., 0.08010424, 0.18117097,
        0.1617243 ],
       [0.01584756, 0.28824811, 1.        , ..., 0.05165773, 0.05618509,
        0.12893887],
       ...,
       [0.1387288 , 0.08010424, 0.05165773, ..., 1.        , 0.07113412,
        0.02067643],
       [0.08450515, 0.18117097, 0.05618509, ..., 0.07113412, 1.        ,
        0.11219793],
       [0.0521102 , 0.1617243 , 0.12893887, ..., 0.02067643, 0.11219793,
        1.        ]])

In [ ]:
similarity_score.shape

(574, 574)

In [ ]:
np.where(pt.index=='Zoya')[0][0]

572

In [ ]:
similarity_score[572]

array([0.08450515, 0.18117097, 0.05618509, 0.        , 0.12130332,
       0.12002722, 0.18038241, 0.07964585, 0.10747393, 0.        ,
       0.07683963, 0.10451125, 0.15123937, 0.06376172, 0.10225546,
       0.06920863, 0.12430432, 0.        , 0.13966838, 0.09944049,
       0.12387251, 0.        , 0.06079419, 0.06592343, 0.07374677,
       0.07315419, 0.29211693, 0.        , 0.14930223, 0.04864357,
       0.23654271, 0.12105456, 0.20677283, 0.        , 0.08418729,
       0.04150011, 0.05496539, 0.06490454, 0.        , 0.08516975,
       0.09928503, 0.12355296, 0.09816427, 0.10811493, 0.        ,
       0.10859037, 0.08525656, 0.        , 0.13518812, 0.02533055,
       0.0614817 , 0.        , 0.0543633 , 0.32381256, 0.        ,
       0.08995824, 0.        , 0.11470099, 0.02907595, 0.14258125,
       0.02416828, 0.10013127, 0.20494537, 0.15549632, 0.15934137,
       0.05010235, 0.06144134, 0.03953361, 0.        , 0.03128323,
       0.26871134, 0.22039184, 0.15688888, 0.        , 0.10378194,
       0.04837374, 0.19931533, 0.08926074, 0.        , 0.06373857,
       0.1878425 , 0.05238647, 0.12990804, 0.1557388 , 0.16185409,
       0.09186603, 0.        , 0.0740503 , 0.07366381, 0.08061936,
       0.130387  , 0.        , 0.05951612, 0.17301456, 0.        ,
       0.27148377, 0.12002722, 0.05662635, 0.09092823, 0.30735738,
       0.16922729, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08655167, 0.24734364, 0.07372591, 0.10516445,
       0.12552142, 0.20655911, 0.12328226, 0.07443545, 0.25855197,
       0.09416367, 0.        , 0.09892844, 0.14095876, 0.13429529,
       0.14048767, 0.057888  , 0.07533178, 0.0787711 , 0.1172918 ,
       0.10081613, 0.14261146, 0.2179214 , 0.06059087, 0.07491817,
       0.14602869, 0.12531009, 0.        , 0.07863993, 0.11995203,
       0.        , 0.08375579, 0.06135395, 0.07046896, 0.15362458,
       0.1046373 , 0.07716105, 0.05180213, 0.14823324, 0.        ,
       0.        , 0.20961295, 0.09524573, 0.63518224, 0.03893268,
       0.44875869, 0.04295206, 0.02977301, 0.10780383, 0.12091338,
       0.06922743, 0.        , 0.15859633, 0.10386522, 0.18767549,
       0.11418739, 0.06314496, 0.        , 0.13415492, 0.3674529 ,
       0.        , 0.05056655, 0.07068682, 0.13411472, 0.16453517,
       0.11454841, 0.        , 0.08567673, 0.06678368, 0.09964556,
       0.12038553, 0.10277071, 0.0512328 , 0.07782315, 0.05263496,
       0.09819454, 0.14963991, 0.39609242, 0.08331793, 0.        ,
       0.10687334, 0.10181818, 0.23264929, 0.22277269, 0.18424122,
       0.19941662, 0.        , 0.07536618, 0.1405647 , 0.11258344,
       0.06208823, 0.17045763, 0.05146502, 0.        , 0.09177375,
       0.08116373, 0.18550246, 0.19188011, 0.05214435, 0.15579736,
       0.18744245, 0.11952286, 0.11462502, 0.0937019 , 0.03776282,
       0.06466436, 0.10474459, 0.12898296, 0.        , 0.11400042,
       0.11540707, 0.19577557, 0.15473449, 0.16505857, 0.        ,
       0.04702729, 0.12422991, 0.1799928 , 0.11301982, 0.0782841 ,
       0.11470554, 0.47474604, 0.14088455, 0.20230733, 0.14497365,
       0.05758731, 0.19567272, 0.05990076, 0.03936562, 0.12681503,
       0.09107508, 0.10618826, 0.22665377, 0.07931469, 0.29139043,
       0.10145993, 0.04486145, 0.05953937, 0.09625176, 0.13233863,
       0.07483315, 0.15254614, 0.        , 0.06189199, 0.07758346,
       0.41108655, 0.02029848, 0.04095315, 0.1010692 , 0.19398531,
       0.        , 0.08414739, 0.10833525, 0.32419447, 0.26644981,
       0.19958974, 0.        , 0.10386896, 0.05258222, 0.09331713,
       0.        , 0.22202769, 0.05543015, 0.04449951, 0.13003443,
       0.07017926, 0.        , 0.13649071, 0.18735369, 0.        ,
       0.09055613, 0.31664881, 0.0351237 , 0.14459886, 0.20703326,
       0.07745967, 0.14055682, 0.16532089, 0.19705927, 0.        ,
       0.0774637 , 0.08593129, 0.12126988, 0.08103564, 0.        ,
       0.09130913, 0.12766543, 0.13895575, 0.0711129 , 0.        ,
       0.        , 0.21624157, 0.25574157, 0.05904376, 0.08623666,
       0.27132671, 0.03666759, 0.        , 0.11163126, 0.03770381,
       0.        , 0.05315859, 0.09219309, 0.12350783, 0.02647406,
       0.        , 0.        , 0.19097173, 0.06611427, 0.        ,
       0.06808183, 0.        , 0.        , 0.        , 0.0938953 ,
       0.0761725 , 0.0848736 , 0.04648111, 0.10826325, 0.04197377,
       0.19333873, 0.17360646, 0.14450601, 0.21490784, 0.14717224,
       0.08029551, 0.0697582 , 0.54455699, 0.06289004, 0.12016122,
       0.07475755, 0.07090792, 0.        , 0.06229918, 0.07284283,
       0.09563034, 0.        , 0.06823283, 0.059192  , 0.21205842,
       0.095723  , 0.        , 0.11881483, 0.13238513, 0.10555345,
       0.06223759, 0.167639  , 0.07606388, 0.10276354, 0.        ,
       0.05956099, 0.        , 0.13429827, 0.05266484, 0.04086742,
       0.10888679, 0.23916448, 0.01647315, 0.06585046, 0.05919384,
       0.0860663 , 0.        , 0.07528372, 0.        , 0.28266302,
       0.        , 0.13098552, 0.        , 0.13081081, 0.07897065,
       0.        , 0.18800653, 0.11284867, 0.11251992, 0.02876105,
       0.        , 0.        , 0.13834643, 0.0443607 , 0.06803889,
       0.09055613, 0.07574402, 0.12410934, 0.        , 0.        ,
       0.03032792, 0.19422401, 0.08174239, 0.        , 0.04854103,
       0.08256538, 0.16385441, 0.14594841, 0.06143354, 0.04743416,
       0.13542085, 0.12629325, 0.07198237, 0.09876374, 0.27937283,
       0.        , 0.18610969, 0.        , 0.13153717, 0.09849282,
       0.07446499, 0.0568301 , 0.        , 0.        , 0.09869329,
       0.        , 0.16284988, 0.07000818, 0.12407388, 0.15950645,
       0.18879274, 0.10275662, 0.10270458, 0.10708467, 0.09288036,
       0.1092278 , 0.17064029, 0.07414462, 0.11095104, 0.01887897,
       0.0959134 , 0.07312618, 0.        , 0.05127358, 0.02669002,
       0.        , 0.08837822, 0.06380093, 0.07687551, 0.04194781,
       0.16446701, 0.1084546 , 0.14229115, 0.07586371, 0.05360004,
       0.14197957, 0.02315937, 0.15542806, 0.13880442, 0.06885979,
       0.04645684, 0.16095715, 0.3154497 , 0.08529805, 0.16077917,
       0.09899495, 0.05838558, 0.07926939, 0.        , 0.08230324,
       0.        , 0.        , 0.09083589, 0.06516211, 0.        ,
       0.111919  , 0.18800387, 0.19238055, 0.06512068, 0.20212837,
       0.06450204, 0.09243895, 0.10394639, 0.03080469, 0.10452573,
       0.2617725 , 0.09452922, 0.        , 0.21381144, 0.14391008,
       0.10543101, 0.0934818 , 0.12192979, 0.07619067, 0.12492673,
       0.        , 0.0730595 , 0.04435343, 0.13077306, 0.28519   ,
       0.        , 0.09060103, 0.10808235, 0.07834573, 0.12511975,
       0.13037584, 0.00743462, 0.07991019, 0.0852679 , 0.        ,
       0.06556101, 0.10057897, 0.17090025, 0.09352288, 0.08064109,
       0.14264161, 0.05577734, 0.07624939, 0.06653009, 0.12310163,
       0.04479761, 0.18775009, 0.03448652, 0.20431838, 0.05189414,
       0.05000945, 0.15886345, 0.08682431, 0.        , 0.16839059,
       0.18385542, 0.11442878, 0.11980431, 0.08738433, 0.        ,
       0.21789108, 0.10897929, 0.02760113, 0.05893105, 0.17963377,
       0.1231983 , 0.08861469, 0.12215176, 0.12056485, 0.0758019 ,
       0.26998022, 0.09445509, 0.06440079, 0.30568656, 0.16118664,
       0.07907196, 0.10178519, 0.14873431, 0.13118625, 0.07721384,
       0.37008772, 0.22313861, 0.14433414, 0.107249  , 0.11802882,
       0.09922779, 0.        , 0.08137335, 0.        , 0.16089107,
       0.17834943, 0.        , 0.03516523, 0.14174986, 0.        ,
       0.10266565, 0.1393642 , 0.08034598, 0.06406596, 0.07424621,
       0.15167299, 0.12499981, 0.06098996, 0.04407946, 0.03781782,
       0.19507854, 0.07113412, 1.        , 0.11219793])

In [ ]:
list(enumerate(similarity_score[572]))

[(0, 0.08450514541026985),
 (1, 0.18117096889512557),
 (2, 0.05618509139751553),
 (3, 0.0),
 (4, 0.12130332273982208),
 (5, 0.12002722014325586),
 (6, 0.1803824135719733),
 (7, 0.07964584754011404),
 (8, 0.1074739250572861),
 (9, 0.0),
 (10, 0.07683962531287639),
 (11, 0.1045112463766223),
 (12, 0.151239366355879),
 (13, 0.06376172032052645),
 (14, 0.10225545732129379),
 (15, 0.06920862534461934),
 (16, 0.12430432345101279),
 (17, 0.0),
 (18, 0.139668379239175),
 (19, 0.099440494855805),
 (20, 0.12387250841187064),
 (21, 0.0),
 (22, 0.06079419381140399),
 (23, 0.06592342530872156),
 (24, 0.07374676740918987),
 (25, 0.07315419219824298),
 (26, 0.29211692874942435),
 (27, 0.0),
 (28, 0.14930223194106992),
 (29, 0.048643572885825236),
 (30, 0.2365427107051284),
 (31, 0.12105455632679274),
 (32, 0.20677283054273748),
 (33, 0.0),
 (34, 0.08418729120241368),
 (35, 0.04150011007470491),
 (36, 0.05496539461342595),
 (37, 0.06490453869368054),
 (38, 0.0),
 (39, 0.08516974821122049),
 (40, 0.09928502920692635),
 (41, 0.12355295760657993),
 (42, 0.09816426667433362),
 (43, 0.1081149332072708),
 (44, 0.0),
 (45, 0.1085903682164183),
 (46, 0.08525656352638096),
 (47, 0.0),
 (48, 0.13518811697782532),
 (49, 0.025330551289786434),
 (50, 0.061481704595757594),
 (51, 0.0),
 (52, 0.05436329564281742),
 (53, 0.3238125579924954),
 (54, 0.0),
 (55, 0.08995824336397944),
 (56, 0.0),
 (57, 0.11470098916961535),
 (58, 0.02907594586628823),
 (59, 0.1425812461886411),
 (60, 0.02416828418123431),
 (61, 0.10013127119874217),
 (62, 0.20494536873680913),
 (63, 0.1554963166046448),
 (64, 0.15934136738933286),
 (65, 0.050102354252463475),
 (66, 0.06144134211425751),
 (67, 0.03953360701826711),
 (68, 0.0),
 (69, 0.03128323475440206),
 (70, 0.26871133596114133),
 (71, 0.22039183618990837),
 (72, 0.15688887551310632),
 (73, 0.0),
 (74, 0.10378194445361194),
 (75, 0.04837374393404703),
 (76, 0.1993153305323544),
 (77, 0.08926073982886736),
 (78, 0.0),
 (79, 0.06373857350899127),
 (80, 0.18784250225577345),
 (81, 0.05238646860120088),
 (82, 0.12990803501314155),
 (83, 0.15573879667178228),
 (84, 0.16185408958127698),
 (85, 0.09186602914609979),
 (86, 0.0),
 (87, 0.07405029556315955),
 (88, 0.07366380786483473),
 (89, 0.0806193640838538),
 (90, 0.13038700475899861),
 (91, 0.0),
 (92, 0.05951612113283926),
 (93, 0.17301456384495598),
 (94, 0.0),
 (95, 0.27148377052843997),
 (96, 0.12002722014325586),
 (97, 0.056626353999530664),
 (98, 0.09092822765088988),
 (99, 0.3073573772282381),
 (100, 0.16922728884161561),
 (101, 0.0),
 (102, 0.0),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.08655166896379315),
 (107, 0.24734363876769008),
 (108, 0.07372591361276858),
 (109, 0.10516444802558823),
 (110, 0.12552142052114573),
 (111, 0.20655911179772893),
 (112, 0.12328226056470712),
 (113, 0.07443544882918908),
 (114, 0.25855196666612407),
 (115, 0.09416367125427225),
 (116, 0.0),
 (117, 0.09892843614848433),
 (118, 0.14095875608787553),
 (119, 0.13429529049420785),
 (120, 0.14048767429393869),
 (121, 0.05788799971836834),
 (122, 0.07533177846892133),
 (123, 0.07877109519591527),
 (124, 0.11729179717514517),
 (125, 0.10081613187175248),
 (126, 0.1426114587577523),
 (127, 0.2179214045102422),
 (128, 0.060590872436613506),
 (129, 0.07491816932821246),
 (130, 0.1460286916249788),
 (131, 0.12531009029835327),
 (132, 0.0),
 (133, 0.07863993120756581),
 (134, 0.11995202878081343),
 (135, 0.0),
 (136, 0.08375578912458892),
 (137, 0.06135395104341616),
 (138, 0.07046895654547515),
 (139, 0.1536245818998133),
 (140, 0.10463730461571237),
 (141, 0.07716104885569097),
 (142, 0.05180213429190015),
 (143, 0.14823324246066938),
 (144, 0.0),
 (145, 0.0),
 (146, 0.2096129496297456),
 (147, 0.09524572892746302),
 (148, 0.6351822403100669),
 (149, 0.03893267642829782),
 (150, 0.44875868727078516),
 (151, 0.0429520606964589),
 (152, 0.029773010610350106),
 (153, 0.10780383102082085),
 (154, 0.12091338478450854),
 (155, 0.0692274253953137),
 (156, 0.0),
 (157, 0.15859633074272256),
 (158, 0.10386522025508915),
 (159, 0.187675491150487),
 (160, 0.11418738848893287),
 (161, 0.06314495579086976),
 (162, 0.0),
 (163, 0.13415491600161406),
 (164, 0.36745290122053004),
 (165, 0.0),
 (166, 0.05056654532254794),
 (167, 0.07068681988902949),
 (168, 0.13411472418906167),
 (169, 0.16453517315279395),
 (170, 0.11454841296209167),
 (171, 0.0),
 (172, 0.08567672841626654),
 (173, 0.06678367811011768),
 (174, 0.099645561602727),
 (175, 0.12038552574281092),
 (176, 0.10277070625636872),
 (177, 0.051232799490872054),
 (178, 0.07782315106448164),
 (179, 0.052634958722116536),
 (180, 0.09819454372082838),
 (181, 0.14963990627997917),
 (182, 0.3960924191971547),
 (183, 0.08331792833582057),
 (184, 0.0),
 (185, 0.10687334289668037),
 (186, 0.10181818181818182),
 (187, 0.2326492921992528),
 (188, 0.222772686270483),
 (189, 0.18424121634359364),
 (190, 0.19941662491192186),
 (191, 0.0),
 (192, 0.07536618488289137),
 (193, 0.14056469879706013),
 (194, 0.11258343514291191),
 (195, 0.06208822558752386),
 (196, 0.17045762760069663),
 (197, 0.05146502354656655),
 (198, 0.0),
 (199, 0.09177374785907313),
 (200, 0.08116373492650468),
 (201, 0.1855024603359688),
 (202, 0.19188011238294053),
 (203, 0.05214434995882486),
 (204, 0.15579736344163883),
 (205, 0.18744244842146893),
 (206, 0.11952286093343936),
 (207, 0.11462502472986216),
 (208, 0.09370189619999118),
 (209, 0.037762821921601936),
 (210, 0.06466435787676753),
 (211, 0.10474458731327635),
 (212, 0.12898296311736604),
 (213, 0.0),
 (214, 0.11400041632994337),
 (215, 0.1154070706079516),
 (216, 0.19577557485493224),
 (217, 0.154734494201616),
 (218, 0.16505857291792744),
 (219, 0.0),
 (220, 0.04702728554075233),
 (221, 0.12422991131825593),
 (222, 0.17999280043197122),
 (223, 0.11301982420347072),
 (224, 0.07828409563871994),
 (225, 0.11470553781788992),
 (226, 0.47474604033830703),
 (227, 0.14088455025801508),
 (228, 0.2023073283225367),
 (229, 0.14497364757281248),
 (230, 0.057587310603477895),
 (231, 0.19567272453270135),
 (232, 0.05990075697767813),
 (233, 0.03936562102789795),
 (234, 0.12681502782419474),
 (235, 0.09107508356512767),
 (236, 0.10618826338966723),
 (237, 0.22665376640276994),
 (238, 0.07931469265628945),
 (239, 0.29139042875814963),
 (240, 0.10145993123917847),
 (241, 0.04486145243337983),
 (242, 0.059539372862367566),
 (243, 0.09625176243854368),
 (244, 0.1323386319768854),
 (245, 0.07483314773547883),
 (246, 0.1525461412270138),
 (247, 0.0),
 (248, 0.06189199376743444),
 (249, 0.07758346381778433),
 (250, 0.4110865489242337),
 (251, 0.02029848381538796),
 (252, 0.040953148394303876),
 (253, 0.10106920259582071),
 (254, 0.1939853056770642),
 (255, 0.0),
 (256, 0.08414738700392639),
 (257, 0.10833525255477916),
 (258, 0.324194473510924),
 (259, 0.266449809298645),
 (260, 0.19958974315773464),
 (261, 0.0),
 (262, 0.10386896411611928),
 (263, 0.05258222401279412),
 (264, 0.09331713384812353),
 (265, 0.0),
 (266, 0.22202769263381605),
 (267, 0.055430150937189955),
 (268, 0.04449950770027698),
 (269, 0.13003443428887476),
 (270, 0.07017925765586443),
 (271, 0.0),
 (272, 0.13649071457616424),
 (273, 0.1873536870631647),
 (274, 0.0),
 (275, 0.09055613299573087),
 (276, 0.3166488071442371),
 (277, 0.035123699580576546),
 (278, 0.14459886199496708),
 (279, 0.20703326353216725),
 (280, 0.07745966692414832),
 (281, 0.14055681735679929),
 (282, 0.16532089477342699),
 (283, 0.1970592712592192),
 (284, 0.0),
 (285, 0.0774637015970122),
 (286, 0.08593128677327967),
 (287, 0.12126987663357873),
 (288, 0.0810356418145724),
 (289, 0.0),
 (290, 0.09130912600075357),
 (291, 0.12766543446031797),
 (292, 0.13895575135389893),
 (293, 0.07111290284199343),
 (294, 0.0),
 (295, 0.0),
 (296, 0.21624157016324747),
 (297, 0.25574156919639646),
 (298, 0.059043763497130995),
 (299, 0.08623666404708409),
 (300, 0.27132671368394057),
 (301, 0.03666759052790285),
 (302, 0.0),
 (303, 0.11163126113028762),
 (304, 0.03770381301494347),
 (305, 0.0),
 (306, 0.05315859494794494),
 (307, 0.0921930927383157),
 (308, 0.12350782559525558),
 (309, 0.026474064574955217),
 (310, 0.0),
 (311, 0.0),
 (312, 0.19097173284079144),
 (313, 0.06611427406099196),
 (314, 0.0),
 (315, 0.06808182676114923),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09389529557231417),
 (320, 0.07617250062839884),
 (321, 0.08487360165999187),
 (322, 0.04648111258522642),
 (323, 0.10826324506755808),
 (324, 0.04197377458376824),
 (325, 0.19333873324249354),
 (326, 0.17360646458428486),
 (327, 0.14450601225429946),
 (328, 0.2149078374328827),
 (329, 0.14717224095693893),
 (330, 0.08029550685469662),
 (331, 0.06975820307714158),
 (332, 0.5445569890608882),
 (333, 0.06289003856472537),
 (334, 0.12016122398758744),
 (335, 0.07475755343782238),
 (336, 0.07090791888705981),
 (337, 0.0),
 (338, 0.06229918232859787),
 (339, 0.0728428263322223),
 (340, 0.09563033666322933),
 (341, 0.0),
 (342, 0.06823282549530918),
 (343, 0.059192002237786576),
 (344, 0.2120584157404014),
 (345, 0.09572299944293472),
 (346, 0.0),
 (347, 0.11881482901604953),
 (348, 0.13238513218473663),
 (349, 0.10555345244238011),
 (350, 0.06223759142641419),
 (351, 0.1676390025483224),
 (352, 0.07606388292556648),
 (353, 0.1027635384150731),
 (354, 0.0),
 (355, 0.059560988173612384),
 (356, 0.0),
 (357, 0.13429827211699724),
 (358, 0.05266483557042951),
 (359, 0.040867421472207614),
 (360, 0.10888678846955498),
 (361, 0.23916448214165786),
 (362, 0.016473147640729775),
 (363, 0.06585046078685182),
 (364, 0.059193839329149275),
 (365, 0.08606629658238704),
 (366, 0.0),
 (367, 0.07528371991317254),
 (368, 0.0),
 (369, 0.2826630208779077),
 (370, 0.0),
 (371, 0.13098551810991607),
 (372, 0.0),
 (373, 0.1308108108108108),
 (374, 0.07897065047448727),
 (375, 0.0),
 (376, 0.1880065336442151),
 (377, 0.11284867198076323),
 (378, 0.1125199180081721),
 (379, 0.028761052210711832),
 (380, 0.0),
 (381, 0.0),
 (382, 0.13834643473411712),
 (383, 0.04436069753671345),
 (384, 0.06803889048073146),
 (385, 0.09055613299573087),
 (386, 0.07574401964082748),
 (387, 0.12410934195510619),
 (388, 0.0),
 (389, 0.0),
 (390, 0.030327923756469186),
 (391, 0.19422400769285125),
 (392, 0.08174238913695991),
 (393, 0.0),
 (394, 0.04854103006331302),
 (395, 0.08256537973448522),
 (396, 0.16385440983525945),
 (397, 0.14594840712136947),
 (398, 0.061433535793679606),
 (399, 0.04743416490252569),
 (400, 0.13542085238306387),
 (401, 0.12629324538937087),
 (402, 0.07198237382159724),
 (403, 0.09876374247349934),
 (404, 0.279372833911726),
 (405, 0.0),
 (406, 0.18610968787357096),
 (407, 0.0),
 (408, 0.1315371672761741),
 (409, 0.09849282156427461),
 (410, 0.0744649893710617),
 (411, 0.05683009892813188),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0986932880775682),
 (415, 0.0),
 (416, 0.16284988353264546),
 (417, 0.07000818183591936),
 (418, 0.12407388117623966),
 (419, 0.15950645031567748),
 (420, 0.188792742453198),
 (421, 0.10275661807846032),
 (422, 0.10270458077650052),
 (423, 0.10708466630811825),
 (424, 0.09288035617599817),
 (425, 0.10922780323369319),
 (426, 0.1706402948784972),
 (427, 0.07414461649840451),
 (428, 0.11095104465544392),
 (429, 0.01887896921484516),
 (430, 0.0959133951220993),
 (431, 0.0731261837701378),
 (432, 0.0),
 (433, 0.05127357854733793),
 (434, 0.026690020925996184),
 (435, 0.0),
 (436, 0.08837822038323186),
 (437, 0.06380093477370127),
 (438, 0.0768755144100829),
 (439, 0.04194781171914594),
 (440, 0.16446700662393515),
 (441, 0.10845460105452372),
 (442, 0.14229115179617988),
 (443, 0.0758637053830981),
 (444, 0.05360003889346638),
 (445, 0.141979567217226),
 (446, 0.023159372369257337),
 (447, 0.1554280603780357),
 (448, 0.13880441875771343),
 (449, 0.0688597912585283),
 (450, 0.04645684204635594),
 (451, 0.16095714928888344),
 (452, 0.3154497040973175),
 (453, 0.08529805141829194),
 (454, 0.16077916961893066),
 (455, 0.09899494936611666),
 (456, 0.0583855829669852),
 (457, 0.07926939108909796),
 (458, 0.0),
 (459, 0.0823032449595965),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0908358927247981),
 (463, 0.06516210954174732),
 (464, 0.0),
 (465, 0.11191899642134825),
 (466, 0.18800386843215366),
 (467, 0.192380551719351),
 (468, 0.06512068164433518),
 (469, 0.20212837443672144),
 (470, 0.06450204371692196),
 (471, 0.09243894811206689),
 (472, 0.103946385976919),
 (473, 0.030804693794977193),
 (474, 0.10452572728574495),
 (475, 0.26177249810538006),
 (476, 0.09452922364796736),
 (477, 0.0),
 (478, 0.21381144096320207),
 (479, 0.14391008428720536),
 (480, 0.10543101146562311),
 (481, 0.0934817964265928),
 (482, 0.12192978743939267),
 (483, 0.0761906720727732),
 (484, 0.12492673011845452),
 (485, 0.0),
 (486, 0.07305950062660078),
 (487, 0.044353427674728114),
 (488, 0.13077306057278865),
 (489, 0.2851899951494325),
 (490, 0.0),
 (491, 0.09060103205012075),
 (492, 0.10808234981180359),
 (493, 0.078345728009542),
 (494, 0.12511975094555342),
 (495, 0.130375836228869),
 (496, 0.007434618191900271),
 (497, 0.07991018894904668),
 (498, 0.08526790393351484),
 (499, 0.0),
 (500, 0.06556100681071858),
 (501, 0.10057896913499395),
 (502, 0.17090025322311295),
 (503, 0.09352288038280891),
 (504, 0.08064109414578811),
 (505, 0.14264161379571125),
 (506, 0.0557773351022717),
 (507, 0.07624938541180445),
 (508, 0.06653008827918488),
 (509, 0.12310163492554921),
 (510, 0.04479761085779634),
 (511, 0.18775008583980288),
 (512, 0.034486524735750264),
 (513, 0.20431838361113652),
 (514, 0.051894135392224074),
 (515, 0.0500094509026456),
 (516, 0.15886344544036302),
 (517, 0.08682431421244592),
 (518, 0.0),
 (519, 0.16839058626030312),
 (520, 0.18385542391076867),
 (521, 0.11442878012218133),
 (522, 0.11980431145477767),
 (523, 0.08738432634459282),
 (524, 0.0),
 (525, 0.21789108168193455),
 (526, 0.10897928500669322),
 (527, 0.027601132232932767),
 (528, 0.05893104629186778),
 (529, 0.17963377378134335),
 (530, 0.12319829652915831),
 (531, 0.08861469461982081),
 (532, 0.1221517606568933),
 (533, 0.12056485041858951),
 (534, 0.07580190194686551),
 (535, 0.26998022221701634),
 (536, 0.09445508916481044),
 (537, 0.06440079495221906),
 (538, 0.3056865630170229),
 (539, 0.1611866373973714),
 (540, 0.07907195767894241),
 (541, 0.10178518558632856),
 (542, 0.14873431400496734),
 (543, 0.13118625380353746),
 (544, 0.07721384063956271),
 (545, 0.3700877157747239),
 (546, 0.2231386087988046),
 (547, 0.14433413849765803),
 (548, 0.10724899728128173),
 (549, 0.11802882199544532),
 (550, 0.09922778767136678),
 (551, 0.0),
 (552, 0.0813733471206735),
 (553, 0.0),
 (554, 0.16089106651757204),
 (555, 0.17834943024797378),
 (556, 0.0),
 (557, 0.03516522515123297),
 (558, 0.1417498615724684),
 (559, 0.0),
 (560, 0.10266565165352041),
 (561, 0.13936419903923117),
 (562, 0.08034598156316901),
 (563, 0.0640659561897158),
 (564, 0.07424621202458749),
 (565, 0.1516729865061038),
 (566, 0.12499980627648684),
 (567, 0.060989958766099646),
 (568, 0.044079459625120485),
 (569, 0.03781781544193006),
 (570, 0.19507854032683056),
 (571, 0.07113412137959381),
 (572, 1.0),
 (573, 0.11219792534101504)]

In [ ]:
np.where(pt.index=='1984')[0][0]

0

In [ ]:
#lamba is used to sort acc. to the similarity score
sorted(list(enumerate(similarity_score[0])),key=lambda x:x[1],reverse=True)[1:6]

[(433, 0.3166375533412213),
 (514, 0.28195011538876225),
 (439, 0.2775401170783511),
 (67, 0.2731957063983398),
 (384, 0.2609981780284909)]

In [ ]:
#to recommend 5 books
def recommend(book_name):
  #index fetch from book name
  index=np.where(pt.index==book_name)[0][0]
  similar_items=sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]
  data=[]
  for i in similar_items:
    item=[]
    #print(pt.index[i[0]])
    temp_df=books[books['Book-Title']==pt.index[i[0]]]
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
    item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL'].values))
    data.append(item)
  return data

In [ ]:
recommend('1984')

[["The Handmaid's Tale",
  'Margaret Atwood',
  'https://images.amazon.com/images/P/0449212602.01.LZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'https://images.amazon.com/images/P/0345313860.01.LZZZZZZZ.jpg'],
 ['The Hours : A Novel',
  'Michael Cunningham',
  'https://images.amazon.com/images/P/0312243022.01.LZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'https://images.amazon.com/images/P/0060809833.01.LZZZZZZZ.jpg'],
 ["The Bonesetter's Daughter",
  'Amy Tan',
  'https://images.amazon.com/images/P/0399146431.01.LZZZZZZZ.jpg']]

In [ ]:
popular_df['Image-URL'][0]

'https://images.amazon.com/images/P/0439136350.01.LZZZZZZZ.jpg'

In [ ]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [ ]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_score.pkl','wb'))